"""Bench tools — printed aids that are NOT movement parts (log 0027).

winding_knob: the ratchet with a finger knob on top. It replaces the
ratchet on the barrel arbor's square so the mainspring can be wound
directly, with the click doing its normal job, while the crown-and-stem
train is redesigned. It is also the instrument for the one number that
redesign needs: how many turns of wind the train actually wants, and
how stiff the spring feels getting there.

Lives in exports/k1/print/bench/ with a generated README, outside the
kit MANIFEST (same convention as the fit coupons).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from build123d import export_stl

from calibers.k1 import revc_parts as rp

README = """\
# Caliber K1 — bench tools (generated by tools/export_bench_tools.py)

Not movement parts. Not in the kit MANIFEST.

## winding_knob.stl

The ratchet with a finger knob grown on top: wind the barrel directly.

- **Print:** PLA, Class B settings (0.12 layers, 4 walls, 100% infill),
  **ratchet teeth DOWN on the plate**, no supports (the flare is 45 deg).
- **It needs the log-0027 parts with it:** the barrel arbor with the
  solid 3.4 mm square, and the pull-pawl click. An older knob on the
  older hollow square slips off under load — that was bench round 1.
- **Fit:** leave the crown wheel and its stud out — as drawn they
  cannot mesh with the ratchet and only add drag. The stem can stay in
  the bridge as a dummy. Press the knob onto the arbor square, teeth
  in the pocket. The fit is snug on purpose: press it fully home.
- **Wind:** turn the knob COUNTER-clockwise looking down at the bridge.
  The click ticks over each tooth and holds when you let go. With a
  log-0028 spring, wind until it goes solid and stop there (the table
  below says how many teeth that is for each strip) — it is sized so
  that solid is inside the PETG's safe strain. Never force past solid.
- **Let down:** hold the knob and wind it a hair further to take the
  load off the hook, push the click's hooked end outward with a
  fingernail, and let the knob turn back slowly in your fingers.
- **Remove:** a O3 pin down the knob's centre hole pushes the arbor
  free if the square grips.

## mainspring_t1.4.stl, mainspring_t2.0.stl — the strip ladder (log 0028)

The torque the train needs with the balance running is still
unmeasured, so the mainspring comes in three strip thicknesses; the
kit's mainspring.stl is the middle one. Same ring, keyway, root and tab
on all three — only the strip changes, so they swap in the drum without
touching anything else. **PETG only, hole side UP on the bed**, walls
only, 100% infill.

{ladder}

Start with the kit's 1.7. If the escapement will not run on it at full
wind, go to 2.0; if it runs and you want more hours, try 1.4. Report
which ones run, and for how long from solid — that number sizes the
real crown-and-stem winding and tells us whether rev D needs a bigger
drum ratio or a steel strip.

## What bench round 1 found (Oct 2026)

Half a turn of wind loads the spring heavily and runs the bare train
for about 15 seconds. Just under one turn the spring is solid. The
first arbor square (1.6 tall, hollow) let the ratchet climb off, and
the first click did not hold. Both are redesigned; see
docs/log/0027-keyless-works-autopsy.md.

## What to report back next

1. Does the click tick while winding and hold when you let go?
2. With the balance in: how many teeth of wind before it runs, and how
   long does a 12-tooth (half-turn) wind last?
3. Anything that slips, creaks or deforms as the wind builds.
"""


def main():
    out = "exports/k1/print/bench"
    os.makedirs(out, exist_ok=True)
    export_stl(rp.ratchet_knob_c(), f"{out}/winding_knob.stl", tolerance=0.02)
    rungs = []
    for t in rp.MAINSPRING_LADDER:
        if t == rp.SPRING_C["strip_t"]:
            continue                         # that one is the kit's mainspring.stl
        name = f"mainspring_t{t:.1f}.stl"
        export_stl(rp.mainspring_c(t), f"{out}/{name}", tolerance=0.02)
        rungs.append(name)
    with open(f"{out}/README.md", "w") as f:
        f.write(README.format(ladder=_ladder_table()))
    print(f"wrote winding_knob.stl, {', '.join(rungs)} + README -> {out}/")


def _ladder_table():
    rows = ["| strip | printed coils | turns to solid | ratchet teeth | N·mm per turn | N·mm at solid | strain at solid | file |",
            "|---|---|---|---|---|---|---|---|"]
    for t in rp.MAINSPRING_LADDER:
        L = rp.mainspring_layout(t)
        kit = t == rp.SPRING_C["strip_t"]
        stop = (f"{24 * L['turns']:.0f} (solid)" if L["turns_safe"] >= L["turns"] - 1e-9
                else f"**stop at {24 * L['turns_safe']:.0f}**")
        rows.append(f"| {t:.1f} | {L['coils']:.1f} | {L['turns']:.2f} | {stop} | {L['k_per_turn']:.0f} | "
                    f"{L['torque_full']:.0f} | {100 * L['strain_full']:.1f}% | "
                    f"{'exports/k1/print/mainspring.stl (the kit)' if kit else 'bench/mainspring_t%.1f.stl' % t} |")
    return "\n".join(rows)


if __name__ == "__main__":
    main()
